something: 123456789
newThing: this-one-is-not-new-any-more
andThis: 27345825462384582354858
newOne: heyDev
anotherNewOne: heyDevAgainAgain
yetAnother: "{{ github.sha }}" # should just be code, not a mistake, just a test
latestSha: 255d83248ae806da36f5065e463547fbc24e588b
